workflows:
  build_android:
    name: Build Android
    max_build_duration: 60
    environment:
      node: 14
      android:
        image: latest
    scripts:
      - name: Install dependencies
        script: yarn install
      # Omitir pruebas para verificar si el problema está en las pruebas
      # - name: Run tests
      #   script: yarn test
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - s24hseguridad@gmail.com
